name: cms-infra

services:
  cms-infra-database:
    image: postgres:latest
    restart: unless-stopped
    container_name: cms-infra-database
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - "../init-db:/docker-entrypoint-initdb.d" # выполнение кастомных скриптов инициализации
      - "cms-infra-database:/var/lib/postgresql/data"
    networks:
      - cms-store-network
  cms-infra-s3:
    image: minio/minio:latest
    restart: unless-stopped
    container_name: cms-infra-s3
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    command: server /data --console-address ":9001"
    #    ports:
    #      - "9000:9000"
    #      - "9001:9001"
    volumes:
      - "cms-infra-s3:/data"
    networks:
      - cms-store-network
  cms-infra-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    container_name: cms-infra-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    #    ports:
    #      - "22181:2181"
    networks:
      - cms-store-network
  cms-infra-kafka:
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped
    container_name: cms-infra-kafka
    environment:
      - KAFKA_BROKER_ID=1 # уникальный номер инстанса
      - KAFKA_ZOOKEEPER_CONNECT=cms-infra-zookeeper:2181 # подключение к zookeeper
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://cms-infra-kafka:9092,PLAINTEXT_HOST://localhost:29092 # задаются слушатели
      # слушатель PLAINTEXT для внутреннего взаимодействия, PLAINTEXT_HOST для подключений извне
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT # оба типа слушателей используют протокол PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT # какой слушатель для внутреннего взаимодействия
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 # количество реплик
      - KAFKA_CLUSTER_ID=-KhL6czPT5e_oBJQkmSmpA
    ports:
      - "29092:29092"
    depends_on:
      - cms-infra-zookeeper
    networks:
      - cms-store-network
  cms-infra-nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: cms-infra-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../nginx:/etc/nginx/conf.d"
    depends_on:
      - cms-backend-auth
      #      - cms-backend-user
      - cms-manage-kafka-ui
    networks:
      - cms-store-network