name: cms-store-backend

include:
  - ./compose/compose-infra.yaml
  - ./compose/compose-init.yaml
  - ./compose/compose-manage.yaml
  - ./compose/compose-backend.yaml
  - ./compose/compose-doc.yaml


