spring:
  application:
    name: swagger

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: microservice-auth
        url: /v3/api-docs/microservice-auth
      - name: microservice-catalog
        url: /v3/api-docs/microservice-catalog
    path: /swagger