spring:
  application:
    name: microservice-catalog
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/catalog_service}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

s3:
  accessKey: ${S3_ACCESS_KEY:user}
  secretKey: ${S3_SECRET_KEY:password}
  bucket: ${S3_BUCKET:images}
  url: ${S3_URL:http://localhost:9000}

#logging:
#  level:
#    software.amazon.awssdk: TRACE
